# Generated by Django 3.2.15 on 2022-11-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0008_auto_20210910_0940'),
        ('site_configuration', '0009_tahoe_fields_update'),
    ]

    operations = [
    ]
