# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-06 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsembler_sites', '0003_remove_email_uniqueness'),
        ('appsembler_sites', '0002_add_hide_linked_accounts_sass_var'),
    ]

    operations = [
    ]
