language: python
python:
  - "2.7"

services:
  - mongodb

node_js: 6

cache:
  directories:
    - $HOME/edxapp_toxenv/
  pip: true
  npm: true

before_install:
  - sudo rm -f /etc/boto.cfg
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install python-dev libxml2-dev libxmlsec1-dev

install:
  - pip install tox tox-pip-version

env:
  global:
    # Avoid caching edx-platform's entry_points
    - TRAVIS_FIXES="pip install -r requirements/edx/local.in"
  jobs:
    - TOXENV=pep8
    - TOXENV=py27-common
    - TOXENV=py27-lms-1
    - TOXENV=py27-lms-2
    - TOXENV=py27-mte
    - TOXENV=py27-studio

script:
  - tox $ARGS

branches:
  # Reduce our TravisCI usage by skipping all pull request branches to reduce effect on the environment (earth),
  # so `continuous-integration/travis-ci/push` shouldn't be built anymore.
  only:
  - /^appsembler\/(tahoe|hawthorn)\/(develop|master)$/
