# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credential_criteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentiallocatorcriterion',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='credentiallocatorcriterions', to='credential_criteria.CredentialCriteria'),
        ),
    ]
