"""
Constants for the credential_criteria Django app.
"""

CREDENTIAL_CRITERION_TYPE_COMPLETION = u'Completion'
CREDENTIAL_CRITERION_TYPE_SCORE = u'Score'
CREDENTIAL_CRITERION_TYPE_GRADE = u'Letter Grade'
CREDENTIAL_CRITERION_TYPE_PASSFAIL = u'Pass/Fail'
CREDENTIAL_CRITERION_TYPE_ENROLLMENT = u'Enrollment'
CREDENTIAL_CRITERION_TYPE_CREDENTIAL = u'Credential'


CREDENTIAL_CRITERION_TYPES = {
    CREDENTIAL_CRITERION_TYPE_COMPLETION,
    CREDENTIAL_CRITERION_TYPE_SCORE,
    CREDENTIAL_CRITERION_TYPE_GRADE,
    CREDENTIAL_CRITERION_TYPE_PASSFAIL,
    CREDENTIAL_CRITERION_TYPE_ENROLLMENT,
    CREDENTIAL_CRITERION_TYPE_CREDENTIAL
}

# TODO: i18n
CREDENTIAL_CRITERION_TYPE_VERBS = {
    CREDENTIAL_CRITERION_TYPE_COMPLETION: "completed",
    CREDENTIAL_CRITERION_TYPE_SCORE: "scored at least {percent}%",
    CREDENTIAL_CRITERION_TYPE_GRADE: "achieved a grade of better than {letter_grade}",
    CREDENTIAL_CRITERION_TYPE_PASSFAIL: "passed",
    CREDENTIAL_CRITERION_TYPE_ENROLLMENT: "enrolled",
    CREDENTIAL_CRITERION_TYPE_CREDENTIAL: "earned"
}
