
def plugin_settings(settings):

    settings.CREDENTIAL_CONFERRING_BLOCK_TYPES = set(settings.ENV_TOKENS.get(
        'CREDENTIAL_CONFERRING_BLOCK_TYPES',
        settings.CREDENTIAL_CONFERRING_BLOCK_TYPES,
    ))

    settings.CREDENTIAL_CRITERIA_ROUTING_KEY = settings.ENV_TOKENS.get(
        'CREDENTIALS_GENERATION_ROUTING_KEY',
        settings.CREDENTIAL_CRITERIA_ROUTING_KEY
    )
