name: Dispatch Notify

on:
  push:
    branches:
      - main
      - prod

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: appsembler/edx-configs
          event-type: edx-platform-${{ steps.extract_branch.outputs.branch }}
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
