name: Develop -> Master PR
on:
  push:
    branches:
      - hawthorn/main
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "hawthorn/main"
          PULL_REQUEST_BRANCH: "hawthorn/prod"
          PULL_REQUEST_TITLE: "Tahoe Hawthorn `develop` -> `master` (production)"
          PULL_REQUEST_BODY: |
            This is an automated pull request from branch `hawthorn/main` into `hawthorn/prod` (production).
            Please review the changes and merge this pull request _before_ running the Tahoe production Cloud Build deployment.
          PULL_REQUEST_REVIEWERS: "johnbaldwin melvinsoft OmarIthawi thraxil"
  hawthorn-to-juniper-sync:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "hawthorn/main"
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_TITLE: "Update Tahoe Juniper (`main`) with Hawthorn changes from `develop`"
          PULL_REQUEST_BODY: |
            This is an automated pull request from branch `hawthorn/main` (Hawthorn) into `main` (Juniper).
            This is meant for making sure all of our Hawthorn changes gets merge into Juniper otherwise Juniper would stall.
            If tests passes merge this pull request.
            If there are merge conflicts, it needs to be resolved manually in a seperate pull request.
          PULL_REQUEST_REVIEWERS: "johnbaldwin melvinsoft OmarIthawi thraxil"

