name: edx-platform tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    runs-on: ubuntu-18.04
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    strategy:
      matrix:
        python-version: [3.5]
        tox-env:
          - pep8
          - common
          - lms-1
          - lms-2
          - mte
          - studio

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.tox-env }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      # TODO: Remove tox-pip-version once we upgrade to Koa+, or whenever we have addressed pip 20.3 strict issues.
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python-dev libxml2-dev libxmlsec1-dev
        pip install tox tox-pip-version
    - name: Run tox
      run: |
        PYTEST_ARGS='--cov=.' tox -e ${{ matrix.tox-env }}
        if [ -f reports/.coverage ]; then mv reports/.coverage reports/.coverage-${{ matrix.tox-env }}; fi
    - name: Upload coverage data
      uses: actions/upload-artifact@v2
      with:
        name: coverage-data
        path: "reports/*coverage*"
        if-no-files-found: ignore
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@v20201129
      if: ${{ matrix.tox-env != 'pep8' }}
      with:
        parallel: true
        flag-name: Unit Test

  coverage:
    name: Diff coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0  # TODO: Consider changing to 1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.5
      - run: python -m pip install --upgrade coverage==5.1 diff-cover==2.6.1

      - name: Download coverage data
        uses: actions/download-artifact@v2
        with:
          name: coverage-data
          path: reports

      - name: Combine and run diff-cover
        # TODO: use `coverage report --fail-under=100` once we understand our coverage and get it to a reasonable diff.
        run: |
          coverage combine reports/.coverage-*
          coverage xml -o reports/combined-coverage.xml

          git fetch origin open-release/juniper.master
          diff-cover reports/combined-coverage.xml --compare-branch=origin/open-release/juniper.master --html-report=diff-coverage.html

          REPORT="$(coverage report)"
          echo "${REPORT}"

          REPORT="${REPORT//'%'/'%25'}"
          REPORT="${REPORT//$'\n'/'%0A'}"
          REPORT="${REPORT//$'\r'/'%0D'}"
          echo "::set-output name=conflict_report::${REPORT}"

      # TODO: Parse and comment $REPORT while linking to `diff-coverage.html` and hide previous coverage comments.

      - name: Upload diff-cover coverage
        uses: actions/upload-artifact@v2
        with:
          name: diff-coverage.html
          path: diff-coverage.html

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls finished
      uses: AndreMiras/coveralls-python-action@v20201129
      with:
        flag-name: Unit Tests
        parallel-finished: true
