name: edx-platform tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    runs-on: ubuntu-18.04
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    strategy:
      matrix:
        python-version: [3.5]
        tox-env:
          - pep8
          - common
          - lms-1
          - lms-2
          - mte
          - studio

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.tox-env }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      # TODO: Remove tox-pip-version once we upgrade to Koa+, or whenever we have addressed pip 20.3 strict issues.
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python-dev libxml2-dev libxmlsec1-dev
        pip install tox tox-pip-version
    - name: Run tox
      run: |
        PYTEST_ARGS='--cov=.' tox -e ${{ matrix.tox-env }}
    - name: Coveralls parallel
      uses: coverallsapp/github-action@1.1.3
      if: ${{ matrix.tox-env != 'pep8' }}
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: tox ${{ matrix.tox-env }}
        parallel: true

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
